# Generated by Django 6.0.4 on 2026-04-21 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0003_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="contact_info",
            field=models.CharField(
                blank=True,
                help_text="Your email, phone, Discord handle, etc. — shown to interested students.",
                max_length=255,
            ),
        ),
    ]
